main/urls.py
from django.urls import path
from .views import MainIndex, PostCreate

app_name = 'main'
urlpatterns = [
    path("", MainIndex.as_view(), name="index"),
    path("create/", PostCreate.as_view(), name= "create")
]

news/urls.py
from django.contrib import admin
from django.urls import path, include
import debug_toolbar
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('user/', include('user.urls')),
    path('__debug__/', include('debug_toolbar.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.urls import path
from .views import UserRegestration, user_login, user_logout, user_info, user_info_post

app_name = "user"
urlpatterns = [
    path('regestration/', UserRegestration.as_view(), name = 'regestration'),
    path('login/', user_login, name='login'),
    path("logout/", user_logout, name='logout'),
    path("info/", user_info, name="info"),
    path("info/save/", user_info_post, name="info_save")
]

main/models.py
from django.db import models
from pathlib import Path
from datetime import datetime
import os
from PIL import Image
from io import BytesIO
from django.core.files import File
def name_conv_fn(ins, file):
    ext = file.split(".")[-1]
    filename = '{:%Y-%m-%d-%H-%M-%S}.{}'.format(datetime.now(), ext)
    return os.path.join('Post', filename)
class Post(models.Model):
    user = models.ForeignKey('user.User', on_delete= models.RESTRICT)
    subject = models.CharField(max_length=200)
    content = models.TextField()
    image = models.ImageField(upload_to= name_conv_fn)
    added_at = models.DateField(auto_now_add=True)
    update_at = models.DateField(auto_now=True)
    def save(self, *args, **kwargs):
        if not self.image.closed:
            img = Image.open(self.image)
            img.thumbnail((500, 500), Image.ANTIALIAS)

            tmp = BytesIO()
            img.save(tmp, 'PNG')
            self.image = File(tmp, 't.png')

        return super().save(*args, **kwargs)

    class Meta:
        verbose_name = "Post"
        verbose_name_plural = "Postlar"

        index_together = (
            ('user', 'added_at'),
            ('added_at', ),
        )

main/views.py
import requests
from django.shortcuts import render, redirect
from django.db.models import Q
from django.views.generic import TemplateView, CreateView, ListView
from .models import Post
from sphinxapi import SphinxClient
from django.contrib.auth.decorators import permission_required
from django.core.exceptions import PermissionDenied
def get_spx_results(wanted):
    spx = SphinxClient()
    spx.SetServer("localhost", 9312)
    spx.SetLimits(0, 1000000, 1000000)
    result = spx.Query(wanted, index='mytest')
    return result

class MainIndex(ListView):
    model = Post
    template_name = 'main/index.html'
    paginate_by = 6
    ordering = "-added_at"

    def get_context_data(self, **kwargs):
        if self.request.GET:
            subject = self.request.GET.get("subject")
            subject = str(subject).replace("+", " ")
            result = get_spx_results(subject)
            if result and result['status'] == 0 and result['total']:
                matches = {row.get('id'):row.get('weight') for row in result['matches']}
                list = [p for p in Post.objects.filter(Q(id__in=matches.keys()) & Q(subject__icontains=subject)).order_by("-added_at")]
            else:
                list = Post.objects.order_by("-added_at")

        else:
            list = Post.objects.order_by("-added_at")
        context = super().get_context_data(**kwargs)
        context['object_list'] = list
        return context


class PostCreate(CreateView):
    model = Post
    fields = ["subject", "content", "image"]
    success_url = "/"

    def dispatch(self, request, *args, **kwargs):
        if not request.user.has_perm("main.add_post"):
            raise PermissionDenied()

        return super().dispatch(request, *args, **kwargs)
    def setup(self, request, *args, **kwargs):
        super().setup(request, *args, **kwargs)

        request.title = "Post qoishish"
    def form_valid(self, form):
        form.instance.user = self.request.user
        super().form_valid(form)
        return redirect("main:index")

main/templates/forms.html
{% extends 'layout.html' %}
{% load static crispy_forms_tags %}
{% block content %}
    <div class="row">
        <div class="col-lg-6 offset-lg-3">
            <div class="card">
                <div class="card-header">
                    {{ request.title }}
                </div>
                <div class="card-body">
                    <form method="post" action="" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form | crispy}}
                        <button type="submit" class="btn btn-secondary mt-4">{% block btn_title %}Saqlash{% endblock %}</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

main/templates/layout.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet", type="text/css", href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}"/>
    <link rel="stylesheet", type="text/css", href="{% static 'vendor/bootstrap/css/bootstrap-grid.min.css' %}"/>
    <link rel="stylesheet", type="text/css", href="{% static 'vendor/bootstrap-icons/bootstrap-icons.css' %}"/>
    <link rel="stylesheet", type="text/css", href="{% static 'main/main.css' %}"/>
    <title>{{ title }}</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg bg-success navbar-dark">
        <div class="container">
            <a class="navbar-brand" href="{% url "main:index" %}">News</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#id-main-menu">
            <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="id-main-menu">
                <ul class="navbar-nav ms-auto">
                    {% if user.is_authenticated %}
                        <li class="nav-item">
                            <a class="nav-link active" style="text-transform: capitalize" href="{% url 'user:info' %}">{{ user.username }}</a>
                        </li>
                        {% if perms.main.add_post %}
                        <li class="nav-item">
                            <a class="nav-link active" href="{% url 'main:create' %}">Post qo'shish</a>
                        </li>
                        {% endif %}
                        <li class="nav-item">
                            <a class="nav-link active" href="{% url 'user:logout' %}">Chiqish</a>
                        </li>
                    {% else %}
                        <li class="nav-item">
                            <a class="nav-link {% if url_name == 'user:regestration' %}active{% endif %}" href="{% url 'user:regestration' %}">Ro'yxatdan o'tish</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link {% if url_name == 'user:login' %}active{% endif %}" href="{% url 'user:login' %}">Tizimga kirish</a>
                        </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>

    <div class="container mt-4">
        {% if messages %}
                {% for message in messages %}
                    <div class="{{ message.tags }} alert-dismissible fade show" role="alert">
                        {{ message }}
                        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                    </div>
                {% endfor %}
        {% endif %}
        {% block content %}

        {% endblock %}
    </div>

    <script src="{% static 'vendor/jquery.js' %}"></script>
    <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.js' %}"></script>
    <script src="{% static 'main/main.js' %}"></script>
</body>
</html>